# -*- coding: utf-8 -*-
"""GAUSSIANNB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxYg1annSWsmp1CBHM_5_QFCyTnTeSRE
"""

pip install snowflake-connector-python

import pandas as pd
import numpy as np
import snowflake.connector
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

conn=snowflake.connector.connect(
    user='your_username',
    password='your_password',
    account='your_acc_id',
    database='your_db_name',
    schema='PUBLIC',
    warehouse='COMPUTE_WH'
)


df = pd.read_sql('SELECT * FROM "your_table_name"', conn)
conn.close()

df.info()

for col in df.columns:
  print(df[col].name,df[col].value_counts().unique())

df.describe()

df.head(5)

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le=LabelEncoder()

x=df.drop('DRUG',axis=1)
y=le.fit_transform(df['DRUG'])

onc=OneHotEncoder(handle_unknown='ignore')
cat_col=x.select_dtypes(include=['string','object']).columns
num_col=x.select_dtypes(include=['int','float']).columns
x_enc=onc.fit_transform(x[cat_col])
x_col=onc.get_feature_names_out(cat_col)
x_encoded=pd.DataFrame(x_enc.toarray(),columns=x_col)
x_tfmd=pd.concat([x[num_col],x_encoded],axis=1)

x_tfmd.head(5)

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
x_train,x_test,y_train,y_test=train_test_split(x_tfmd,y,test_size=0.2,random_state=29,stratify=y)
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
pd.Series(y_test).value_counts(normalize=True)

from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import matthews_corrcoef,roc_auc_score,balanced_accuracy_score
print("maththews score ",matthews_corrcoef(y_test, y_pred))
print("roc score",roc_auc_score(y_test,model.predict_proba(x_test,multi_class='ovr',average='macro')))
print("balc acc score",balanced_accuracy_score(y_test, y_pred))

